# This file containt the ws Server routes

#Auth routes
login:
    service: App\Service\WsServerApp\WsSecurity
    method: login
    tokenSecurity: false

checkSecureConnection:
    service: App\Service\WsServerApp\WsSecurity
    method: checkSecureConnection
    tokenSecurity: true

#Register routes
register:
    service: App\Business\RegisterBusiness
    method: register
    tokenSecurity: false

# Battle routes
newBattle:
    service: App\Business\BattleBusiness
    method: newBattle

findBattle:
    service: App\Business\BattleBusiness
    method: findBattle

setCardsSelection:
    service: App\Business\BattleBusiness
    method: setCardsSelection

showThrowAnnouncement:
    service: App\Business\BattleBusiness
    method: showThrowAnnouncement

battleMovement:
    service: App\Business\BattleBusiness
    method: battleMovement

# BattleList routes
getUserBattleList:
    service: App\Business\ListBattleBusiness
    method: getUserBattleList

refuseBattle:
    service: App\Business\ListBattleBusiness
    method: refuseBattle

acceptBattle:
    service: App\Business\ListBattleBusiness
    method: acceptBattle

# Cards routes
getUserCards:
    service: App\Business\CardBusiness
    method: getUserCards

getGameCards:
    service: App\Business\CardBusiness
    method: getGameCards

addCard:
    service: App\Business\CardBusiness
    method: addCard

#User routes
getUsers:
    service: App\Business\UserBusiness
    method: getUsers